version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-node
        environment:
          BUNDLER_VERSION: 2.0.1
      
    steps:
      - checkout

      - run: 
          name: Bundle Install
          command: |
            gem update --system
            gem uninstall bundler
            rm /usr/local/bin/bundle
            rm /usr/local/bin/bundler
            gem install bundler
            bundle install

      - run:
          name: Tests
          command: |
            bundle exec rspec

      - store_artifacts:
          path: coverage